baseURL = 'https://banggeul-portfolioooo.netlify.app'
languageCode = 'en-US'
title = 'Bang Geul Han's Portfolio Website'

[[menus.main]]
name = 'Projects'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

#[[menus.main]]
#name = 'Projects'
#pageRef = '/projects'
#weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20



[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
